// CSE 154 ASCIIMation
//Jiaqi Zhang; AJ; HW07
// This is my custom animation - "Flower" to be used by the overall program.
// It was automatically generated by the StringMaker tool.


var CUSTOM =
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"{o}\n" + 
"\\| \n" + 
"=====\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"\n" + 
" {o} \n" + 
"\\ | \n" + 
" \\| \n" + 
"=====\n" +  
"\n" + 
"\n" + 
"\n" + 
"\n" + 
"    _,-._\n" + 
"   / \\_/ \\    \n" + 
"   >-(_)-<    \n" + 
"   \\_/ \\_/\n" + 
"     `-\'\n" + 
"     \\|     \n" + 
"      |\n" + 
"      |/\n" + 
"=====\n" + 

"     __\n" + 
"  __/  \\__\n" + 
" /  \\__/  \\\n" + 
" \\__/..\\__/\n" + 
" /  \\__/  \\\n" + 
" \\__/  \\__/\n" + 
"    \\__/\n" + 
"     ||\n" + 
"     ||\n" + 
"     ||\n" + 
"  .\'/.\'\\.\'.\n" + 
"..\'.\'..\'..\'.\'.\n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;